# Generated by Django 5.0 on 2024-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job_S1', '0002_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='matricule',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='nom',
            field=models.CharField(default='Grizzlies', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='azangueleonel@gmail.com', max_length=254),
        ),
    ]
