# Generated by Django 5.0 on 2024-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job_S1', '0003_remove_mymodel_classe_remove_mymodel_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
