# Generated by Django 5.0 on 2024-03-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_board_list_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='board',
        ),
        migrations.RemoveField(
            model_name='card',
            name='list',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
