# Generated by Django 5.0 on 2024-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_list_board_remove_card_list_delete_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
