# Generated by Django 5.0 on 2024-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_time_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_remaining',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
