# Generated by Django 5.0 on 2024-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Fora_S2', '0002_conversation_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
