# Generated by Django 5.0 on 2024-05-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Fora_S2', '0004_conversationoo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationoo',
            name='participants',
        ),
        migrations.AddField(
            model_name='conversationoo',
            name='Username',
            field=models.CharField(default='Conver', max_length=200),
        ),
    ]
