# Generated by Django 5.0 on 2024-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('deja_pris', models.BooleanField(default=False)),
            ],
        ),
    ]
