# Generated by Django 5.0 on 2024-04-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
