# Generated by Django 5.0 on 2024-04-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
