# Generated by Django 5.0 on 2024-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job', '0010_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
