# Generated by Django 5.0 on 2024-04-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job', '0011_alter_joboffer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='profile',
            field=models.CharField(default='max', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='remuneration',
            field=models.CharField(default='400', max_length=100),
        ),
    ]
