# Generated by Django 5.0 on 2024-04-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_A_Job', '0012_joboffer_profile_joboffer_remuneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='profile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='remuneration',
            field=models.CharField(max_length=100),
        ),
    ]
